version: '3'

services:
  mongo:
    image: mongo:5.0.22-focal
    ports:
      - 27017:27017
    networks:
      - app_network
    volumes:
      - ipp_mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  ipp_mongo:
    external: true
networks:
  app_network:
    attachable: true
    driver: bridge
